### PR TITLE
 listFinancialEventsAll + listFinancialEventsByNextToken + removed double this bindings

### PR DESCRIPTION
**Pull request by pwrnrd**
@ericblade I'm not sure whether everything went OK with the pull. Our versions seemed somewhat apart, but I tried to convert to your implementation.

In addition, I use a copy (fork) of MWSSimple, so **my package.json and package-lock.json should actually not be pulled by you. I hope you can omit these files as a maintainer from my pull request? The same might hold for some of the parameter updates in the JSDoc comments.**  

If you could change as a maintainer in the next step, then that would be wonderful. Then I'll do a new pull request to make sure that I'm perfectly aligned again :D. The issue regarding the WMSSimple versions will be tough though, but I'll look into that.

Perhaps package-lock.json should be added to .gitignore?

### CODE REVIEW

**Comment by ericblade** [comment]
wow, ok, that looks like a lot right off, i'll try to get to looking at it this weekend.  

re: package-lock.json hmm.. i'm pretty sure there's arguments both for and against including it, and it's entirely possible that i probably shouldn't include it for at least one of the two, but .. i'll need to review that decision.. doesn't sound like a problem to remove it from version control though.

**Comment by ericblade** [comment]
ok, so, I think there's some things here that I understand are probably some pain points, such as the various mis-steps in documentation (really, I had a very strong desire to have very good documentation, and I think I discovered just how hard that is to do!) .. but I don't think I want to accept this whole pull req because with all those commits, there's a lot of changes unrelated to the feature.

This seems like the desired change is pretty well encapsulated -- 
commit b77e303 seems to have what you meant to have pulled in.  Now, I'm not entirely certain on exactly the way to handle that with github, but what I think what would get us there is checking out a new branch based on mine, then cherry-picking commit b77e303 into it, then doing a GitHub pull request on that branch to mine.  

Are there any other changes involved in it?  

so.. something like (assuming you have a remote to my github called 'ericblade' and yours is 'origin')
````
git checkout -b ericmaster ericblade/master
git cherry-pick b77e303
git push origin/ericmaster
````
then do the pull req in GitHub from your ericmaster branch to my master branch

that should make it so that our trees are still relatively compatible at the point where the change is introduced into the tree.

**Comment by pwrnrd** [comment]
Hi Eric,

Thank you very much. Your proposed solution makes sense! I wasn't familiar with cherry-pick. I hoped that GitHub had build in a cherry-pick GUI for the maintainers of the package, but apparently they don't. That's unfortunate, but I'lll follow the steps you proposed and make a new PR.

**Comment by ericblade** [comment]
> GitHub had build in a cherry-pick GUI for the maintainers of the package

If they have, I don't know about it.  I could've done it from the command line in a few minutes, but I figured I'd give you the opportunity, so you get credit for it, if that's something that you're interested in.  

Speaking of credit, if you'd like to add a "contributors" section to package.json, and put yourself in there, feel free https://flaviocopes.com/package-json/#contributors

**Pull request closed without merging**
