### PR TITLE
added isValidOrderId method and exported for usage later - added .ide…

### PR DESCRIPTION
**Pull request by aflansburg**
To my knowledge this is the first pull request I've ever done against someone else's repo so bear with me here.

added isValidOrderId method and exported for usage later - even though I'm not quite sure what that will look like - added `.idea/` to the gitignore even though I know that's not a typical thing to do - it just helps me with commits since the gitignore is part of the repo

### CODE REVIEW

**Comment by ericblade** [comment]
Thanks, Abram!

That looks like it should work, and yes, you should add your local things that you don't want to commit to the .gitignore, for sure, that is there to make devs lives easier, so if you want to ignore ./idea , probably everyone else would too. :)

I'm trying to look over the existing code to see what would be a good way to integrate it that doesn't require adding another loop through everything.  

what if your function was called 'validate()' and we did..
````
    const isValid = (type, test, definition) => {
        let valid = isType(type, test, definition);
        if (valid && definition.validation) {
            valid = validate(test, definition.validation);
        }
        return valid;
    }
````

then called isValid() instead of isType() in the two places where it's used?

Say definition.validation would be an object that might have fields like:
````
    stringFormat: 'amazonOrderId', // or
    minValue: 10, // and/or
    maxValue: 100, // and/or
    stringFormat: 'amazonMarketplaceId', // or ...
....
````

.. then your function would become the base for building verification of format/ranges/etc separately from verifying type of data.

then add a test in test-sanity that looks something like

````
    it('validates 3-7-3 amazonOrderId format', (done) => {
        let result = validate('123-1234567-123', { stringFormat: 'amazonOrderId' });
        expect(result).to.be.(true);
        result = validate('abc-def-ghi', { stringFormat: 'amazonOrderId' });
        expect(result).to.be.(false);
    });
````

**Comment by ericblade** [comment]
oh, also, i think if you add another commit to your repo, that will bring the change into the pull request automatically.  

I think most people suggest that you make a separate branch for each pull request, that way you don't add something to your master, and it gets accidentally bundled into other pull requests.  I remember the way github does that drove me absolutely nuts when I was first figuring it out :-)

**Comment by aflansburg** [comment]
Yep I was reading that too. My next go I’ll checkout a separate branch and
commit that to my fork (which I’ll keep current with your master upstream)
and then do a pull. So on this change if I implement what you’ve suggested
and commit then it should bring that into the existing pull req?

**Comment by ericblade** [comment]
I'm pretty sure that's how it works, yes.

**Comment by aflansburg** [comment]
Submitted a new pull request. Sorry for the confusion.

**Pull request closed without merging**
