### PR TITLE
Added test

### PR DESCRIPTION
**Pull request by pwrnrd**
Added test of the MWS object to see if it is overwritten when created asynchronously.

### CODE REVIEW

**Comment by ericblade** [comment]
just went to pull this in and check it against master, and i'm wondering if there's anything else i need to setup in the repo, to get the eslint rules to enforce? :-)

image

**Comment by pwrnrd** [comment]
@ericblade is it due to tabs? Because then the problem is on my side. I have some global user settings in VS Code to set the tab size.

**Comment by ericblade** [comment]
yeah :) after i run ````npx eslint --fix test-sanity.js```` then it only complains about you shadowing the 'const mws' ..

that test runs just fine in master branch, too. i don't think it functionally differs much from the other test, as it's not really making a request to anywhere... hmmm.

**Comment by ericblade** [comment]
although on one hand, i'd really like to understand where your original code was causing mws-a to fall down, and have a test to ensure that that doesn't happen again.. so far, i've been unsuccessful at building a test that actually fails on the version prior to this patch.  Did the "// some async functions here" part that was obviously snipped out of your sample involve calling any mws functions first?  I definitely recognize that there was a possibility of one unit becoming confused and switching to using the static instance...

but i won't be too worked up about it if there isn't a test that replicates the problem . . the code work was worth it, taking advantage of newer better language features IMO is always good (and i'd happily update to node 10 or 11, but for the fact that one of my work projects utterly fails in anything newer than 8.6, and i don't want to be using nvm 5 times a day)

**Comment by pwrnrd** [comment]
Hmmm, I thought I replied to this, but I can't see my reply, so my reply probably got stuck in my head. 

Anyways, I wanted to say that I agree with you that the test does not offer that much over the existing tests, except that it is async. When I ran the previous version synchronously, it worked. However, when I used an async function to set-up the connections/inits, then the connections seemed to overwrite eachother. Not all of my connection were overwritten, just one or two. I'm not sure whether that behaviour is captured well in this test, I hope so.. 

At the moment I encountered that error I think I did not perform any async activities. Hence, I figured why not just restructure the function that creates the MWS connection/init to behave synchronously and then my code worked. 
So, then I started investigating and thought that some global variable (or another higher scoped variable) was being used and overwritten. Subsequently, I started logging a lot of request and I found that the request left my application correctly, but didn't arrive correctly in MWS Simple. Then I saw how the global variable MWS was used in MWS Advanced, and I thought that it had to do something with that... I wasn't sure, so that's why I created the post. I've been playing around with my app a bit, and everything seems to work brilliantly so far :D!

**Comment by ericblade** [comment]
OK, well, i'm going to go ahead and close this, then, since this test worked fine both in the old one, and in the branch for fixing . . . . i'm not sure there's specific value in testing for this, other than as a historical "make sure it stays fixed" kind of thing, since after the restructuring, it really shouldn't be possible to hit the wrong code path -- you're either calling the static versions of the functions on the class, or you're calling the instance versions on an instance.

**Pull request closed without merging**
