### PR TITLE
implement getInboundGuidanceFor(ASIN|SKU)

### PR DESCRIPTION
**Pull request by ericblade**
not ready for merge, tests and documentation still to be written, clean up of comments, logs, etc.

@pwrnrd @aflansburg anyone else.. was in need of filling in some of the gaps in API coverage, and as I started to dig in to this one, i realized a probably way better way of handling all the parsing duties... basically have a single function that handles each type as the amazon docs have it, and then delegate that off in an upper level parser.  I've been doing that to some degree anyway, but I think that I've finally put together a sane method that doesn't make me gnash my teeth when it's time to bash in a new API.

Not sure if I'll get back to finishing this commit this weekend, but I wanted to see if you guys had any input to it before I went all-in and started making a huge library of small handlers. :-D

The bulk of the new code is https://github.com/ericblade/mws-advanced/pull/119/commits/828e19861dbbb63c4f17f883e8baa2f471892224#diff-e92f260ee53411c4267677a10b7abeb9

### CODE REVIEW

**Comment by ericblade** [comment]
i still need to write tests for it, but i've added jsdoc for the whole setup.  This is the sort of thing that I wish I'd figured out earlier in this process, but glad to have figured out what feels like a good process now, instead of just winging it.

**Comment by pwrnrd** [comment]
Hi @ericblade,

So do you want pass these separate parsers to ``parseEndpoint()`` as ``inParser``?

Would it be good for readability if we'd create "outParser" / "inParser" which contains static methods for all the various parsers?

**Comment by ericblade** [comment]
might be a good idea.. the files in lib/parsers right now are pretty much a righteous mess of experimentation, whereas when i wrote this one, i realized if i write one function for each of the many many types that MWS can return in the XML, then it's going to be a lot easier to fix bugs and accommodate changes.  Also will be able to re-use something like "Money" which shows up in several API returns, in several places (i see it 11 times here on one page of the OrderItem docs, and according to it's entry, it is used in 5 different API calls)

**Comment by pwrnrd** [comment]
I agree; creating common parsers for types such as Address or Money are good ideas in general.

**Comment by ericblade** [comment]
fwiw, i might not be able to test something like Address -- Amazon is applying some access level permissions to people's MWS accounts that will prevent them from accessing certain data. :-S  in my case, I was informed that I'd no longer be able to access identifying information about customers.  They aren't clear on if that only affects when I use the API for other people, or if it also will affect for myself as well. :-S

**Comment by pwrnrd** [comment]
I think that this applies to your own MWS access keys. So if you work for different clients, with different access keys, they'd might still have access to this data. 
Concerning the tests, I think we could still make that work if by mocking the response.

**Comment by ericblade** [comment]
I'm in need of this feature, so I'm going forward with it, I'll figure out what pieces I missed after. Apologies!

**Pull request merged**
