### PR TITLE
README Update

### PR DESCRIPTION
**Pull request by aflansburg**
The samples in the readme threw me off for a second until I realized a few of them mentioned `await` which cannot be used outside of an async function declaration. For instance before: `const result = await mws.getMatchingProductForId({
        MarketplaceId: 'ATVPDKIKX0DER',
        IdType: 'ASIN',
        IdList: [ 'B005NK7VTU' ],
    });
    console.log('Product=', result);`

Removed the `await` to become:
`const result = mws.getMatchingProductForId({
        MarketplaceId: 'ATVPDKIKX0DER',
        IdType: 'ASIN',
        IdList: [ 'B005NK7VTU' ],
    });
    console.log('Product=', result);`

### CODE REVIEW

**Comment by ericblade** [comment]
Much appreciated, although removing the await means you're just going to end up with Promises on the output.  I probably should have thought through the README a little more thoroughly, and been more critical of it.  As it was, I was just reading it trying to figure out where I had left off a couple of months ago, and was pretty confused by it myself.

Could you do me a big favor, though, and re-do this pull request without the extra stuff that was accidentally put in, and the commits to remove it?  I know it comes out the same way, but I'd prefer to have the git history not have that stuff.

Probably now would be a good time for me to figure out a better way to do documentation, other than jamming it all in README too . . . the MWS API is a little bit larger than I anticipated when I started out.

**Comment by aflansburg** [comment]
Right sorry about that. I'm going to close this, make edits and resubmit without all the junk in there. I meant to add the handling of the returned Promises as well.

**Comment by ericblade** [comment]
No worries. I am super excited to have other people interested in working with it.  It'll force me to do better work :) since it's not just me looking at it

**Comment by aflansburg** [comment]
Same - especially since it's something I can use in my day-to-day. :D

**Pull request closed without merging**
